from enum import Enum


class AuditStage(str, Enum):
    INITIALIZING = "INITIALIZING"
    FETCHING_GITHUB = "FETCHING_GITHUB"
    PARSING_SRS = "PARSING_SRS"
    SEMANTIC_MAPPING = "SEMANTIC_MAPPING"
    ANALYZING = "ANALYZING"
    GENERATING_REPORT = "GENERATING_REPORT"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"