"""Initial schema migration for ScopeSense.

This migration creates the four new tables introduced in
`backend/storage/models_extended.py` and adds the `owner_id`
foreign‑key column to the `audit_sessions` table.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "20230608_0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please verify ###
    # add owner_id column (nullable for existing rows)
    op.add_column('audit_sessions', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_audit_sessions_owner_id_users', 'audit_sessions', 'users', ['owner_id'], ['id'])

    # create table audit_results
    op.create_table(
        'audit_results',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('audit_session_id', sa.Integer(), sa.ForeignKey('audit_sessions.id'), nullable=False),
        sa.Column('variance_json', sa.JSON(), nullable=True),
        sa.Column('primary_causes_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # create table finding_records
    op.create_table(
        'finding_records',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('audit_session_id', sa.Integer(), sa.ForeignKey('audit_sessions.id'), nullable=False),
        sa.Column('finding_json', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # create table faq_records
    op.create_table(
        'faq_records',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('audit_session_id', sa.Integer(), sa.ForeignKey('audit_sessions.id'), nullable=False),
        sa.Column('question', sa.Text(), nullable=False),
        sa.Column('answer', sa.Text(), nullable=False),
        sa.Column('category', sa.String(), nullable=True),
        sa.Column('relevance_score', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    # create table chat_messages
    op.create_table(
        'chat_messages',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('audit_session_id', sa.Integer(), sa.ForeignKey('audit_sessions.id'), nullable=False),
        sa.Column('role', sa.String(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please verify ###
    op.drop_table('chat_messages')
    op.drop_table('faq_records')
    op.drop_table('finding_records')
    op.drop_table('audit_results')
    op.drop_constraint('fk_audit_sessions_owner_id_users', 'audit_sessions', type_='foreignkey')
    op.drop_column('audit_sessions', 'owner_id')
    # ### end Alembic commands ###
