from __future__ import annotations

'''backend/models/srs_node.py'''
"""SRS graph node model.

All SRS elements (modules, requirements, sub‑requirements) are represented by a single
`SRSNode` dataclass. The graph is defined via the nullable ``parent_id`` field.
"""



from dataclasses import dataclass, field
from typing import List, Optional, Dict, Any

from backend.models.ownership import OwnershipEvent


@dataclass
class SRSNode:
    """Unified SRS node.

    Attributes
    ----------
    id: str
        Unique identifier for the node (e.g., generated UUID or extracted key).
    parent_id: Optional[str]
        Identifier of the parent node – ``None`` for top‑level modules.
    title: str
        Human‑readable title or name.
    description: str
        Full textual description.
    planned_hours: Optional[float]
        Estimated effort from the SRS document.
    owner_history: List[OwnershipEvent]
        Chronological list of owners/handlers.
    profile_embedding: Optional[List[float]]
        Embedding vector generated by the existing semantic encoder.
    metadata: Dict[str, Any] = field(default_factory=dict)
        Additional arbitrary key‑value data.
    """

    id: str
    parent_id: Optional[str] = None
    title: str = ""
    description: str = ""
    planned_hours: Optional[float] = None
    owner_history: List[OwnershipEvent] = field(default_factory=list)
    profile_embedding: Optional[List[float]] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
